### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by tarikk35** [FedericoDiRosa/react-window-scroller#1]
Hello,

I just started using this package, it works very well and does its job. Much thanks. But the overflow property is causing a small visual bug in react-window  FixedSizeGrid component. This is probably because scrollbar takes some width/height from the grid. I didn't tested other react-window components yet, but it seems like changing overflow property to "unset" solves the visual bug. I don't know if "overflow : hidden" property plays an important role, but if not, changing it would be helpful. Again, thanks for this awesome package.

**Comment by FedericoDiRosa** [comment]
You're right @tarikk35, overflow doesn't need to be hidden. Thanks for reporting the issue!

**Comment by FedericoDiRosa** [comment]
Fixed in v.1.0.6
