### ISSUE TITLE
can not work edge(not chromium version)

### ISSUE THREAD

**Issue by eretica** [FedericoDiRosa/react-window-scroller#4]
thanks for good library

https://github.com/FedericoDiRosa/react-window-scroller/blob/952ca73e93d53fffcba4200529e8f343d76cfad7/src/index.jsx#L15-L16

in edge(not chromium version) above is not working

```
const scrollTop = (document.documentElement.scrollTop || document.body.scrollTop) - offsetTop
const scrollLeft = (document.documentElement.scrollLeft || document.body.scrollLeft) - offsetLeft
```

this one is working

**Comment by FedericoDiRosa** [comment]
@eretica Thanks for reporting the issue! Bugfix deployed in v1.0.7
